### ISSUE TITLE
I ValueError: Could not find the input entity for <telethon.tl.types.PeerChannel ....

### ISSUE THREAD

**Issue by Mafhoom** [iw4p/telegram-cloud#1]
I had Telethon-1.16.4,
but installed pip install telegram_cloud-1.0.3-py3-none-any.whl

**I want to download all pdf files of an public channel thus I used:**

at first: e:\telegram_download\tglogin
...
Traceback (most recent call last):
  File "e:\telegram_download\lib\shutil.py", line 788, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] **The process cannot access the file because it is being used by another process: 'nima.session' -> 'C:\\Users\\user/.telegram-cloud/nima.session'**

and then used :
E:\telegram_download>tgcloud -m download -n nima -u -1001085852697 -p "E:\\telegram_download"  -c "test"
Traceback (most recent call last):
  File "e:\telegram_download\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\telegram_download\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\telegram_download\Scripts\tgcloud.exe\__main__.py", line 7, in <module>
  File "e:\telegram_download\lib\site-packages\telegramcloud\__main__.py", line 60, in cli
    client.loop.run_until_complete(main())
  File "e:\telegram_download\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "e:\telegram_download\lib\site-packages\telegramcloud\__main__.py", line 42, in main
    target_chat = await client.get_entity(int(username))
  File "e:\telegram_download\lib\site-packages\telethon\client\users.py", line 268, in get_entity
    inputs.append(await self.get_input_entity(x))
  File "e:\telegram_download\lib\site-packages\telethon\client\users.py", line 442, in get_input_entity
    raise ValueError(
**ValueError: Could not find the input entity for <telethon.tl.types.PeerChannel object at 0x00000144D495DF70>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.**

**Comment by iw4p** [comment]
Hello, dear Mafhoom
Telegram-cloud is not available for windows now.
Our team is working hard on it and it'll be compatible with windows ASAP.
Stay tuned by watching the repo.
Thanks.

**Comment by iw4p** [comment]
Hi again!
Telegram-cloud (TGCloud) is now available for windows and from now you can use it without any problem, Just follow the readme carefully and if you have any problem, open a new issue.

**Comment by Mafhoom** [comment]
I really thank you for your speed and quality of work, I hope you are always energetic.
The script now works well in Windows. 
I hope you have time to read my questions and needs:

- Is there any download speed limitation from Telegram Cloud or it is unlimited?
- Can I download only the text of the channel in html format without any other files?
- Is ther any option that I can download full channel with html/content and all the files just like telegram export?
- Is it possible to generate an html file with link to the downloaded file and with the caption and description from the main channel file?
- I just want to download the files that I have not downloaded before, while now the script re-downloads the file with a new name. maybe Because there may be two files with the same name but different in size and content, Can You add an option for solve this problem to **synchronize the downloaded directory and channel content**?
- Please show in some way what the current process is and how much is left, This can be for the current file and as well as all the remaining files.
- Can I download several types of files? For example, both pdf and zip in one command?
- Ability to get a list of available files before the download step, for example, get a list that says how many zip files and how many photos and how many pdf and etc.
- Please add ability to give it a list of channels and it can sync all files.


Thank you again

**Comment by iw4p** [comment]
Hello again and your welcome,
Can you please make new issues with good titles about these questions, because if someone wants to search in issues and find answers it's better when questions and titles are related together, And also it avoids duplicate questions, And you'll make me happy if you use Labels on the title.
