### ISSUE TITLE
can I have a list of files in the channel?

### ISSUE THREAD

**Issue by Mafhoom** [iw4p/telegram-cloud#10]
Ability to get a list of available files before the download step, for example, get a list that says how many zip files and how many photos and how many pdf and etc.

**Comment by iw4p** [comment]
Nice idea bruh, Added to the to-do list.

**Comment by iw4p** [comment]
Hello,
From now you can use `tginfo` command to get some useful info.
Examples:
`tginfo -n testSession -u me`
and for search a specific word, try this:
`tginfo -n testSession -u me -s ".pdf"`
