### ISSUE TITLE
可以利用这个库实现一个真正的无限制telegram-drive

### ISSUE THREAD

**Issue by sunzcdev** [iw4p/telegram-cloud#17]
这个库虽然实现了1.5GB的文件的上传与下载，但是我们可以通过文件切分与合并的方式来突破这个限制。因为，每个文件上传后都会返回一个file_id，我们可以将拆分后的子文件块的file_id记录下来，等下载的时候基于这些file_id来下载与合并，最终得到源文件。
另外，我们还需要一个文件管理系统来管理这些文件。每个源文件在文件管理系统都有一个独一无二的路径，并且每个文件还有一系列的file_id组成。基于此就可以实现一个telegram-cloud-drive。并且由于telegram无审查，文件传输速度无限制，文件大小无限制，这个telegram-cloud-drive将可以与Google drive相媲美。不知作者可否有兴趣？
[filebrowser](https://github.com/filebrowser/filebrowser)是个不错的文件管理库。

**Comment by iw4p** [comment]
这是一个好主意，而且从来没有人做过，我真的很喜欢这样做，但是我没有足够的时间和知识来做到这一点，您能帮我扩大这个项目的规模并绕过整个限制吗？
如果您实现了该段合并以及文件浏览器，那将非常有趣。

**Comment by hoganjing** [comment]
加个数据库，实现层级的文件夹功能？

**Comment by iw4p** [comment]
不，我认为该功能可以使用DropBox和OneDrive等电报将大文件分成小块并上传到云中

**Comment by sunzcdev** [comment]
这个功能我用Android实现了。但是遇到几个问题：
1、该不该用数据库。按道理使用telegram的用户都是很注重隐私的，因此这个数据库是不应该有的，即使有也必须在telegram的服务器上。因此我想使用caption与search配合以达到数据库的效果，结果tdapi的search功能总是有延迟。导致，使用的体验比较差。个人使用的话还是推荐有个数据库最为方便。
2、上传后文件下载路径更新比较慢。可能是我对tdapi不熟练导致的。
