### ISSUE TITLE
How to download photos?

### ISSUE THREAD

**Issue by Laesx** [iw4p/telegram-cloud#18]
This might be a bit of a dumb question but how do you exactly download photos that are not a file and have no caption? when I do  -c ".jpg" it only downloads the photos that are files.
Also it's only downloading at 1Mbps, why might this be?

**Comment by iw4p** [comment]
Hello,
For speed problems please check [this issue](https://github.com/iw4p/telegram-cloud/issues/2).
For downloading images you will need something to point that image to tell which one you want to download, the best pointer is a caption, without a caption or something to point, how do you want to say which images should downloaded? Another way is downloading the whole .jpg in conversation.

**Comment by Laesx** [comment]
Yeah I did check that issue before and I have cryptg installed, but it doesn't seem like it's using it because it's still slow.

About the images thing, my use case was to download every single photo and video of a channel to be able to image compare so I don't repost images, as well as having a local archive of absolutely everything, but seems like this can't be done then?

**Comment by iw4p** [comment]
Oh, I have to check it because I didn't have any problem with the speed.
I think it can be done but some codes need changes

**Comment by Laesx** [comment]
Hmm I see, then you can't currently download pictures that are compressed or sent normally not as file and have no caption.

**Comment by iw4p** [comment]
Yes 🌝, But it's possible.
