### ISSUE TITLE
Is there any download speed limitation from Telegram Cloud or it is unlimited?

### ISSUE THREAD

**Issue by Mafhoom** [iw4p/telegram-cloud#2]
of course I must use vpn from my country (And really I don't know why) to connect to telegram, But I feel Telegram cloud has a speed limitation itself, Is it true?
Is it for Download/Upload?

**Comment by iw4p** [comment]
Same, as I know telegram does not limit the speed, the wasted time is for encryption, and you can speed up it with installing cryptg.
`pip install cryptg`

[answer](https://telethonn.readthedocs.io/en/latest/extra/basic/installation.html):
> By default the library will use a pure Python implementation for encryption, which can be really slow when uploading or downloading files. If you don’t mind using a C extension, install cryptg via pip or as an extra:

[more details](https://docs.telethon.dev/en/latest/basic/installation.html):
>If cryptg is installed, the library will work a lot faster, since encryption and decryption will be made in C instead of Python. If your code deals with a lot of updates or you are downloading/uploading a lot of files, you will notice a considerable speed-up (from a hundred kilobytes per second to several megabytes per second if your connection allows it). If it’s not installed, pyaes will be used (which is pure Python, so it’s much slower).

And Also thank you, cryptg added as install_requires when somebody installs the package

**Comment by mithlajkn** [comment]
Same here... I don't know why. I am getting far different up and down speeds for each file. While using VPN getting faster than normal I think it's due to the telegram servers we are connecting . For android - telegramX provides a better download speed than the official app.
