### ISSUE TITLE
无法查询/下载私人频道内的文件

### ISSUE THREAD

**Issue by yinuxy** [iw4p/telegram-cloud#20]
可以使用tgsend给私人频道发送消息，但是却无法使用tginfo，tgcloud去查询和下载频道内的文件，请问这是怎么
回事
![image](https://user-images.githubusercontent.com/42272333/110577992-c41d4300-819e-11eb-99a9-f564d2b922e1.png)

**Comment by InfiniteYinux** [comment]
![image](https://user-images.githubusercontent.com/42272333/110577967-b8ca1780-819e-11eb-9ee1-426907f27704.png)

**Comment by iw4p** [comment]
您确定您可以通过该电报帐户访问该专用频道吗？如果是，请尝试使用其他方式代替chat_id和target_caht。
[Here](https://github.com/iw4p/telegram-cloud/blob/master/telegramcloud/utils/utils.py)
您可以看到 **target_username_handler** 函数的工作以及如何转换实体。也许更改这些行会为您提供帮助。
