### ISSUE TITLE
Uploads to Telegram keeps lots of old copies. Need a way to remote-delete & ideally remote-rename files

### ISSUE THREAD

**Issue by amantotek** [iw4p/telegram-cloud#21]
We uploaded fredNotes.txt in total five times, adding changes each time,
expecting the old remote Telegram file to be overwritten each time.

```
fred@linuxpc:~/python3$ ls -alt *.txt*
-rw-rw-r-- 1 fred fred 13612 Mar 13 18:03 fredNotes.txt
```

Then we download expecting just one file, the latest fredNotes.txt
Instead five files get returned...
```
fred@linuxpc:~/python3$ ls -alt *.txt*
-rw-rw-r-- 1 fred fred 13597 Mar 13 18:27 'fredNotes (4).txt'
-rw-rw-r-- 1 fred fred 13597 Mar 13 18:27 'fredNotes (3).txt'
-rw-rw-r-- 1 fred fred 13597 Mar 13 18:27 'fredNotes (2).txt'
-rw-rw-r-- 1 fred fred 13596 Mar 13 18:27 'fredNotes (1).txt'
-rw-rw-r-- 1 fred fred 13612 Mar 13 18:27  fredNotes.txt
fred@linuxpc:~/python3$
```
This could get out of hand!

Upload code used:
```
      sFullPathAndFile = os.path.abspath(os.getcwd())+'/fredNotes.txt'
      sCmd = '~/.local/bin/tgcloud -m upload -n frednotetotg -u me -p ' + sFullPathAndFile + ' -c "fileid"'
      process = subprocess.Popen(['bash', '-c', sCmd], stdout=subprocess.PIPE)         
      sout, err = process.communicate()    
```                                            

Assuming no upload switch is available e.g. 'overwrite-old-files'=True or 'don't-keep-old-versions' we could work with a delete with, ideally, a rename feature (cp fredNotes.txt fredNotes.txt.old) just to keep one previous version on Telegram
Anyone know if possible to add remote-delete and ideally remote-rename to https://github.com/iw4p/telegram-cloud/ ?

**Comment by iw4p** [comment]
tg-cloud criteria for distinguishing between files is **-c** arg
By the caption, it can figure out which file should be downloaded, That's why you have to use caption when you upload it so later you can retrieve it by the caption.
If you use the same caption for files, it can be a headache when you want to retrieve it and get files like x (1).txt  x (2).txt ...
So change your script the way that you can use different captions for safe download/upload
And also one other thing, If I do not understand what you mean, please explain more precisely. 👻🧘‍♂️

**Comment by amantotek** [comment]
Thx for reply. That is fine when dealing with files (plural) but in above case we just have one file using one caption that is always the same.
Imagine Telegram holds a master file, call it fredNotes.txt. When a device wants to edit or add to that file it downloads the file and could make say 10 changes each time uploading the file back to Telegram. It seems Telegram keeps old versions renaming them with numbers 1 2 3 4 etc as shown above.
Another device later might want to do the same but its initial download results in 10 files, 9 of them being old copies of fredNotes.txt that we no longer need.

So gradually the Telegram account fills with old files we don't want. A remote delete/rename file ability would enable us to prevent that.

Download code used:
```
          #-p For download mode: pass simple directory path like "/Users/nima/Desktop/Iwanttoescapefrom/"
          sPathToPutFile = os.path.abspath(os.getcwd())+'/'
          sCmd = '~/.local/bin/tgcloud -m download -n frednotetotg -u me -p ' + sPathToPutFile + ' -c "fileid"' #Download in same dir as called from                                                 
          process = subprocess.Popen(['bash', '-c', sCmd], stdout=subprocess.PIPE)         
          sout, err = process.communicate()                                                

```
It appears that a download matches up those files with same caption and 'fredNotes (1).txt' 'fredNotes (2).txt' all would have the same caption.

**Comment by iw4p** [comment]
Hello, I updated the package and from now you have the `Delete` and `Edit` feature.
Just run **tgutil** on your terminal.
Also, I updated the readme file, just search for `tgutil`.
Hope this feature helps you.
Have a great day 🧘‍♂️
