### ISSUE TITLE
Uploading file from stdin

### ISSUE THREAD

**Issue by rany2** [iw4p/telegram-cloud#22]
I'm trying to do this but there seems to be some kind of protection to prevent me from upload non-regular files. Could this be removed?

```
$ tar -I zstd -c -C testfolder . | tgcloud -n d -u me -p /proc/self/fd/0 -m upload --caption testfolder.tar.zst
Something went wrong, make sure the directory path is valid.
tar: -: Wrote only 4096 of 10240 bytes
tar: Error is not recoverable: exiting now
```

**Comment by iw4p** [comment]
Seems you have a problem with the path.
Your path should contain your target file, but you just typed the path.
For example:
$ tar -I zstd -c -C testfolder . | tgcloud -n d -u me -p /proc/self/fd/0/testfolder.tar.zst -m upload --caption testfolder.tar.zst

**Comment by rany2** [comment]
`/proc/self/fd/0` is a special file which reads stdin. For example:

`echo aiahaaih | cat /proc/self/fd/0` would result in cat reading out `aiahaaih`. 

<pre>$ ls -l /proc/self/fd/0 /dev/pts/0 
crw--w----. 1 rany tty  136, 0 Mar 27 16:41 <span style="background-color:#171421"><font color="#A2734C"><b>/dev/pts/0</b></font></span>
lrwx------. 1 rany rany     64 Mar 27 16:41 <font color="#2AA1B3"><b>/proc/self/fd/0</b></font> -&gt; <span style="background-color:#171421"><font color="#A2734C"><b>/dev/pts/0</b></font></span>
</pre>

However it seems like this error is coming from telethon and that you have made no checks for regular files 

Edit, not sure if this is an issue with telegram-cloud: https://github.com/LonamiWebs/Telethon/issues/3007#issuecomment-808753057
