### ISSUE TITLE
Speed issue. 

### ISSUE THREAD

**Issue by mishailovic** [iw4p/telegram-cloud#25]
I ran several tests on my virtual server with 2 gigabit internet, and I came to the conclusion that the speed problem is in telethon itself. I wrote a small benchmark: https://gist.github.com/mishailovic/3bc25bb644642acf371e732f2dafa52f and the pyrogram speed was almost three times faster.

```
Pyrogram stats: speed - 168.88 Mbps, time - 71 s
Telethon stats: speed - 55.85 Mbps, time - 215 s
```

I think it would be nice to rewrite the scripts in pyrogram.

**Comment by iw4p** [comment]
Wow, It was a great comparison. 🤔
I really like to switch on Pyrogram but I can't do this soon because of my hand problem. 
It worth migrating to Pyrogram instead of cleaning and rewriting the whole package, because my codes are suck and really dirty...
BTW I will be happy if you give me a hand.
And again thanks for your useful comparison. 🤗

**Comment by mishailovic** [comment]
I'll do a couple more tests, maybe it's a problem of my server, or something else. I hope if I pass the exams successfully, I will definitely help you 😁

**Comment by iw4p** [comment]
Hmm, I knew the Telethon is slow even with cryptg package, have you ever checked it out?
But I've never use Pyrogram, I just heard about that.
Thanks 😛, I've to rest for a month... After that, I'll back to my keyboard.
Do you need my Telegram ID?

**Comment by mishailovic** [comment]
I think yes, if I need to write to you about anything, I will text you inside Telegram

**Comment by iw4p** [comment]
Sure, text me [Here](https://T.me/AutisticBruh)

**Comment by mishailovic** [comment]
Hey! It's me again. So, thought that it is better not to rewrite the entire project to another library, it will take a lot of time and effort, and will not give the desired result. Instead, I decided to do parallel uploading via telethon, and here are the results I have achieved:
![Снимок экрана 2021-06-01 в 11 33 55](https://user-images.githubusercontent.com/41520056/120295063-77de2c80-c2cf-11eb-9262-b1949eab456b.png)

I used code from this gist:
https://gist.github.com/painor/7e74de80ae0c819d3e9abcf9989a8dd6/

**Comment by iw4p** [comment]
Hello again,
Seems it’s faster than Pyrogram, isn’t it?
Also I fixed the link of Telegram ID, now you can text me

**Comment by mishailovic** [comment]
> Seems it’s faster than Pyrogram, isn’t it?

This is not entirely true, I think it is possible to implement parallel uploading in pyrogram, but I have no idea how to do it.



> Also I fixed the link of Telegram ID, now you can text me

I know, I just want the discussion to be public, if someone wants to join

**Comment by iw4p** [comment]
Yes the better idea is implements pyrogram with parallel uploading, I have to check the codes carefully and I think it’s possible. 
And also I have to decide about making another python package or mixing them together.

**Comment by mishailovic** [comment]
Good luck!

**Comment by iw4p** [comment]
Thanks buddy 🙏🏻

**Comment by prof-kicks** [comment]
The discussion is too interesting !!

**Comment by iw4p** [comment]
> The discussion is too interesting !!

It will be even more interesting if implemented‌ 👻
