### ISSUE TITLE
What happens to files > 2GB

### ISSUE THREAD

**Issue by BetaTester41** [iw4p/telegram-cloud#30]
I was writing a script to upload my large files, but I was wondering what would happen if I input a file bigger than 2GB. Would the file split by itself and upload, or do I need to split it ahead of time? Thanks in advance!

**Comment by iw4p** [comment]
Hi, 
Unfortunately, I didn't implement the split big files feature, you have to do it by yourself.
and It'd make me happy if you can contribute and implement this feature on telegram-cloud for general uses.
Thanks.

**Comment by BetaTester41** [comment]
I saw another program with this maybe that might work... https://github.com/Nekmo/telegram-upload/issues/3

**Comment by iw4p** [comment]
I don't know they have this feature or not.
Please keep me informed if telegram-upload upload > 2GB is working.
