### ISSUE TITLE
Attempt 6 at connecting failed: TimeoutError: 

### ISSUE THREAD

**Issue by 2144533854** [iw4p/telegram-cloud#31]
I am sure that APP_ID and API_HASH is true. Whats more, the internet can work correctly. After I input tglogin -> APP_ID -> API_HASH , it raised **Attempt 6 at connecting failed: TimeoutError:** . I have no idea to solve it, whats wrong with it?

**Comment by iw4p** [comment]
I have no idea, Try another internet connection and VPN.
