### ISSUE TITLE
Is it possible to download full channel?

### ISSUE THREAD

**Issue by Mafhoom** [iw4p/telegram-cloud#4]
Is ther any option that I can download full channel with html/content and all the files just like telegram export?
If the answer is yes, what is the difference between the script and telegram export function?

**Comment by iw4p** [comment]
Short answer: Telegram export gives you more data.
Yes It's possible to download all of your data, texts, chats, media, and ..., It's like Telegram export but Telegram export gives you what Telegram has from you, but with scripts, you can get and download what you see and what is download-able and save-able.

**Comment by Mafhoom** [comment]
What is the command parameter to fetch full channel?

**Comment by iw4p** [comment]
I have to add an option for it to download full chat media + texts
