### ISSUE TITLE
Can I have the Caption of files too?

### ISSUE THREAD

**Issue by Mafhoom** [iw4p/telegram-cloud#5]
Is it possible to generate an html file with link to the downloaded file and with the caption and description from the main channel file?

**Comment by iw4p** [comment]
I don't understand, can you give me an example?

**Comment by Mafhoom** [comment]
Now when I download files in a directory I have :
01.pdf
02.pdf
03.pdf
04.pdf
...

I want  channel[@test].htm with full html like this:
--------------------------------------------

[01](01.pdf)
a book about **software** engineering
[02](02.pdf)
a book about Data Mining
[03](03.pdf)
a book about python
[04](04.pdf)
a **book** about encryption
....

**Comment by iw4p** [comment]
I see, Labeled as an enhancement.
