### ISSUE TITLE
Is there any option to synch a directory and a channel?

### ISSUE THREAD

**Issue by Mafhoom** [iw4p/telegram-cloud#6]
I just want to download the files that I have not downloaded before, while now the script re-downloads the file with a new name. maybe Because there may be two files with the same name but different in size and content, Can You add an option for solve this problem to synchronize the downloaded directory and channel content?

Telegram export function itself has not this option too and export files again and again with new names.

Is it possible to add this method for upload files too?

**Comment by iw4p** [comment]
Maybe if there are some good unique things to control it like date or ids, and also you can use some scripts to remove duplicate files from a directory by comparing their md5 hashes.

**Comment by Mafhoom** [comment]
I don't know but I saw some sync function in telethon documents
please add some functions for this because it is very important to download channel with huge data.

**Comment by iw4p** [comment]
I'll check.

**Comment by wu2305** [comment]
I have found an similar [repo](https://github.com/Dineshkarthik/telegram_media_downloader) using the file name to identify whether this file has been downloaded
> return not os.path.isdir(file_path) and os.path.exists(file_path)

**Comment by wu2305** [comment]
By the way, I 'm also looking forward the ability to restrict the amount of files to be downloaded by using the message_id. For sometimes the disk space is limited
